version: "3.8"
services:
  mashrooms-mysql:
    container_name: ${APP_NAME}-mysql-${APP_ENV}
    image: 'mysql:8.2.0'
    restart: always
    ports: 
      - ${MYSQL_TCP_PORT}:3306
    env_file: 
      - .env
    networks:
      - registry_default
      - mashrooms-network
    volumes:
      - mashrooms-mysql-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 30

  mashrooms-phpmyadmin:
    image: "phpmyadmin/phpmyadmin:latest"
    restart: always
    ports:
      - 51515:80
    env_file: 
      - .env
    depends_on:
      - mashrooms-mysql
    links: 
      - mashrooms-mysql
    networks:
      - registry_default
      - mashrooms-network
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.mushrooms-api-prod.rule=Host(`${API_PHPMYADMIN_DOMAIN_NAME}`) && PathPrefix(`/`)'
      - 'traefik.http.routers.mushrooms-api-prod.entrypoints=websecure'
      - 'traefik.http.routers.mushrooms-api-prod.tls.certresolver=myresolver'
      - 'traefik.http.routers.mushrooms-api-prod.service=mushrooms-api-prod'
      - 'traefik.http.services.mushrooms-api-prod.loadbalancer.server.port=51515'
    volumes:
      - mashrooms-phpmyadmin-volume:/var/lib/phpmyadmin

  api:
    image: registry.it-flumx.com/flumx_mushrooms_api:latest
    env_file: 
      - .env
    depends_on:
      mashrooms-mysql:
        condition: service_healthy
    links: 
      - mashrooms-mysql
    ports:
      - 51516:3000
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.mushrooms-api-prod.rule=Host(`${API_DOMAIN_NAME}`) && PathPrefix(`/`)'
      - 'traefik.http.routers.mushrooms-api-prod.entrypoints=websecure'
      - 'traefik.http.routers.mushrooms-api-prod.tls.certresolver=myresolver'
      - 'traefik.http.routers.mushrooms-api-prod.service=mushrooms-api-prod'
      - 'traefik.http.services.mushrooms-api-prod.loadbalancer.server.port=3000'
    networks:
      - registry_default
      - mashrooms-network

  mysql-cron-backup:
    image: fradelg/mysql-cron-backup
    depends_on:
      - mashrooms-mysql
    links: 
      - mashrooms-mysql
    networks:
      - registry_default
      - mashrooms-network
    environment:
      - MYSQL_HOST=mashrooms-mysql
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MAX_BACKUPS=15
      - INIT_BACKUP=0
      # Every day at 03:00
      - CRON_TIME=*/5 * * * *
      # Make it small
      - GZIP_LEVEL=9
      # As of MySQL 8.0.21 this is needed
      - MYSQLDUMP_OPTS=--no-tablespaces
    restart: unless-stopped


volumes:
  mashrooms-api-volume:
  mashrooms-mysql-volume:
  mashrooms-phpmyadmin-volume:

networks:
  registry_default:
    external: true
  mashrooms-network:
    name: mashrooms-network

# dockehub actions
# create secrets
