export enum EPermission {
  CREATE_ADMINS = "CREATE_ADMINS",
  READ_ADMINS = "READ_ADMINS",
  UPDATE_ADMINS = "UPDATE_ADMINS",
  DELETE_ADMINS = "DELETE_ADMINS",

  CREATE_CLIENTS = "CREATE_CLIENTS",
  READ_CLIENTS = "READ_CLIENTS",
  UPDATE_CLIENTS = "UPDATE_CLIENTS",
  DELETE_CLIENTS = "DELETE_CLIENTS",

  CREATE_EMPLOYEES = "CREATE_EMPLOYEES",
  READ_EMPLOYEES = "READ_EMPLOYEES",
  UPDATE_EMPLOYEES = "UPDATE_EMPLOYEES",
  DELETE_EMPLOYEES = "DELETE_EMPLOYEES",

  CREATE_DRIVERS = "CREATE_DRIVERS",
  READ_DRIVERS = "READ_DRIVERS",
  UPDATE_DRIVERS = "UPDATE_DRIVERS",
  DELETE_DRIVERS = "DELETE_DRIVERS",
}
