export enum EPermission {
  CREATE_ADMINS = "CREATE_ADMINS",
  READ_ADMINS = "READ_ADMINS",
  UPDATE_ADMINS = "UPDATE_ADMINS",
  DELETE_ADMINS = "DELETE_ADMINS",

  CREATE_CLIENTS = "CREATE_CLIENTS",
  READ_CLIENTS = "READ_CLIENTS",
  UPDATE_CLIENTS = "UPDATE_CLIENTS",
  DELETE_CLIENTS = "DELETE_CLIENTS",
}
