export enum EPermission {
  CREATE_ADMINS = 'CREATE_ADMINS',
  READ_ADMINS = 'READ_ADMINS',
  UPDATE_ADMINS = 'UPDATE_ADMINS',
  DELETE_ADMINS = 'DELETE_ADMINS',

  CREATE_CATEGORIES = 'CREATE_CATEGORIES',
  READ_CATEGORIES = 'READ_CATEGORIES',
  UPDATE_CATEGORIES = 'UPDATE_CATEGORIES',
  DELETE_CATEGORIES = 'DELETE_CATEGORIES',

  CREATE_CLIENTS = 'CREATE_CLIENTS',
  READ_CLIENTS = 'READ_CLIENTS',
  UPDATE_CLIENTS = 'UPDATE_CLIENTS',
  DELETE_CLIENTS = 'DELETE_CLIENTS',

  CREATE_CLIENT_FILES = 'CREATE_CLIENT_FILES',
  READ_CLIENT_FILES = 'READ_CLIENT_FILES',
  DELETE_CLIENT_FILES = 'DELETE_CLIENT_FILES',

  CREATE_EMPLOYEES = 'CREATE_EMPLOYEES',
  READ_EMPLOYEES = 'READ_EMPLOYEES',
  UPDATE_EMPLOYEES = 'UPDATE_EMPLOYEES',
  DELETE_EMPLOYEES = 'DELETE_EMPLOYEES',

  CREATE_EMPLOYEE_DOCUMENTS = 'CREATE_EMPLOYEE_DOCUMENTS',
  READ_EMPLOYEE_DOCUMENTS = 'READ_EMPLOYEE_DOCUMENTS',
  DELETE_EMPLOYEE_DOCUMENTS = 'DELETE_EMPLOYEE_DOCUMENTS',

  CREATE_DRIVERS = 'CREATE_DRIVERS',
  READ_DRIVERS = 'READ_DRIVERS',
  UPDATE_DRIVERS = 'UPDATE_DRIVERS',
  DELETE_DRIVERS = 'DELETE_DRIVERS',

  CREATE_OFFLOADS = 'CREATE_OFFLOADS',
  READ_OFFLOADS = 'READ_OFFLOADS',
  UPDATE_OFFLOADS = 'UPDATE_OFFLOADS',
  DELETE_OFFLOADS = 'DELETE_OFFLOADS',

  CREATE_WORKS = 'CREATE_WORKS',
  READ_WORKS = 'READ_WORKS',
  UPDATE_WORKS = 'UPDATE_WORKS',
  DELETE_WORKS = 'DELETE_WORKS',

  CREATE_PRICES = 'CREATE_PRICES',
  READ_PRICES = 'READ_PRICES',
  UPDATE_PRICES = 'UPDATE_PRICES',
  DELETE_PRICES = 'DELETE_PRICES',

  CREATE_SHIFTS = 'CREATE_SHIFTS',
  READ_SHIFTS = 'READ_SHIFTS',
  UPDATE_SHIFTS = 'UPDATE_SHIFTS',
  DELETE_SHIFTS = 'DELETE_SHIFTS',

  CREATE_WORK_RECORDS = 'CREATE_WORK_RECORDS',
  READ_WORK_RECORDS = 'READ_WORK_RECORDS',
  UPDATE_WORK_RECORDS = 'UPDATE_WORK_RECORDS',
  DELETE_WORK_RECORDS = 'DELETE_WORK_RECORDS',

  CREATE_CHAMBERS = 'CREATE_CHAMBERS',
  READ_CHAMBERS = 'READ_CHAMBERS',
  UPDATE_CHAMBERS = 'UPDATE_CHAMBERS',
  DELETE_CHAMBERS = 'DELETE_CHAMBERS',

  CREATE_VARIETIES = 'CREATE_VARIETIES',
  READ_VARIETIES = 'READ_VARIETIES',
  UPDATE_VARIETIES = 'UPDATE_VARIETIES',
  DELETE_VARIETIES = 'DELETE_VARIETIES',

  CREATE_BATCHES = 'CREATE_BATCHES',
  READ_BATCHES = 'READ_BATCHES',
  UPDATE_BATCHES = 'UPDATE_BATCHES',

  CREATE_WATERINGS = 'CREATE_WATERINGS',
  READ_WATERINGS = 'READ_WATERINGS',
  DELETE_WATERINGS = 'DELETE_WATERINGS',

  CREATE_CUTTINGS = 'CREATE_CUTTINGS',
  READ_CUTTINGS = 'READ_CUTTINGS',

  READ_STORAGES = 'READ_STORAGES',

  CREATE_STORE_CONTAINERS = 'CREATE_STORE_CONTAINERS',
  READ_STORE_CONTAINERS = 'READ_STORE_CONTAINERS',
  UPDATE_STORE_CONTAINERS = 'UPDATE_STORE_CONTAINERS',
  DELETE_STORE_CONTAINERS = 'DELETE_STORE_CONTAINERS',

  READ_YIELDS = 'READ_YIELDS',

  READ_OFFLOAD_RECORDS = 'READ_OFFLOAD_RECORDS',
}
