export enum ERegion {
  KYIV = 'Київська',
  VINNITSA = 'Вінницька',
  VOLYN = 'Волинська',
  DNIPRO = 'Дніпропетровська',
  DONETSK = 'Донецька',
  ZHYTOMYR = 'Житомирська',
  ZAKARPATTYA = 'Закарпатська',
  ZAPORIZHIA = 'Запорізька',
  IVANO_FRANKIVSK = 'Івано-Франківська',
  KROPIVNITSKYI = 'Кіровоградська',
  KRYM = 'Крим',
  LUHANSK = 'Луганська',
  LVIV = 'Львівська',
  MYKOLAYIV = 'Миколаївська',
  ODESA = 'Одеська',
  POLTAVA = 'Полтавська',
  RIVNO = 'Рівненська',
  SUMY = 'Сумська',
  TERNOPIL = 'Тернопільська',
  KHARKIV = 'Харківська',
  KHERSON = 'Херсонська',
  KHMELNYTSKYI = 'Хмельницька',
  CHERKASY = 'Черкаська',
  CHERNIVTSI = 'Чернівецька',
  CHERNIHIV = 'Чернігівська',
}
