import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateSchema1712178180840 implements MigrationInterface {
    name = 'CreateSchema1712178180840'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`waterings\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`volume\` decimal(7,0) NOT NULL DEFAULT '0', \`dateTimeFrom\` datetime NOT NULL, \`dateTimeTo\` datetime NULL, \`target\` enum ('MUSHROOM', 'PEAT') NOT NULL DEFAULT 'MUSHROOM', \`drug\` varchar(50) NULL, \`shiftId\` int NULL, \`batchId\` int NULL, INDEX \`IDX_657441e38570083f56caad3536\` (\`dateTimeFrom\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`shifts\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`dateFrom\` date NOT NULL, \`dateTo\` date NULL, \`returnsKnife\` tinyint NULL DEFAULT 0, \`returnsBedSheets\` tinyint NULL DEFAULT 0, \`returnsWardrobeKey\` tinyint NULL DEFAULT 0, \`paysForKitchen\` tinyint NULL DEFAULT 0, \`kitchenPaymentMethod\` enum ('CARD', 'CASH') NOT NULL DEFAULT 'CASH', \`kitchenExpenses\` decimal(10,2) NOT NULL DEFAULT '0.00', \`calendarDayNumber\` decimal(3,0) NOT NULL DEFAULT '0', \`workingDayNumber\` decimal(3,0) NOT NULL DEFAULT '0', \`wage\` decimal(10,2) NOT NULL DEFAULT '0.00', \`bonus\` decimal(10,2) NOT NULL DEFAULT '0.00', \`customBonus\` decimal(10,2) NOT NULL DEFAULT '0.00', \`customBonusDescription\` varchar(255) NULL, \`wageTotal\` decimal(10,2) NOT NULL DEFAULT '0.00', \`paidAmount\` decimal(10,2) NOT NULL DEFAULT '0.00', \`remainedPayment\` decimal(10,2) NOT NULL DEFAULT '0.00', \`employeeId\` int NOT NULL, INDEX \`IDX_3a0e6f3a0fae1e7fac5ca3801d\` (\`dateTo\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`employees\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`firstName\` varchar(35) NULL, \`lastName\` varchar(35) NULL, \`patronymic\` varchar(35) NULL, \`phone\` varchar(15) NULL, \`bankCard\` varchar(16) NULL, \`region\` enum ('Київська', 'Вінницька', 'Волинська', 'Дніпропетровська', 'Донецька', 'Житомирська', 'Закарпатська', 'Запорізька', 'Івано-Франківська', 'Кіровоградська', 'Крим', 'Луганська', 'Львівська', 'Миколаївська', 'Одеська', 'Полтавська', 'Рівненська', 'Сумська', 'Тернопільська', 'Харківська', 'Херсонська', 'Хмельницька', 'Черкаська', 'Чернівецька', 'Чернігівська') NOT NULL DEFAULT 'Дніпропетровська', \`town\` varchar(35) NULL, \`isActive\` tinyint NULL DEFAULT 0, \`isUnreliable\` tinyint NULL DEFAULT 1, \`hasCriminalRecord\` tinyint NULL DEFAULT 0, INDEX \`IDX_c7496c7e6508db62ba4da839b3\` (\`lastName\`), INDEX \`IDX_cbc362d1c574464a63d3acc3ea\` (\`phone\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`public_file\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`url\` varchar(255) NOT NULL, \`key\` varchar(255) NOT NULL, \`type\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`clients\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`firstName\` varchar(35) NULL, \`lastName\` varchar(35) NULL, \`patronymic\` varchar(35) NULL, \`nickname\` varchar(35) NULL, \`phone\` varchar(15) NULL, \`moneyDebt\` decimal(10,2) NOT NULL DEFAULT '0.00', \`delContainer1_7Debt\` decimal(5,0) NOT NULL DEFAULT '0', \`delContainer0_5Debt\` decimal(5,0) NOT NULL DEFAULT '0', \`delContainer0_4Debt\` decimal(5,0) NOT NULL DEFAULT '0', \`delContainerSchoellerDebt\` decimal(5,0) NOT NULL DEFAULT '0', INDEX \`IDX_8a28b1e0e38fc81165d5dac229\` (\`lastName\`), INDEX \`IDX_aa22377d7d3e794ae4cd39cd9e\` (\`phone\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`drivers\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`firstName\` varchar(35) NULL, \`lastName\` varchar(35) NULL, \`phone\` varchar(15) NULL, INDEX \`IDX_d3a9115337268e2413392a8ac4\` (\`lastName\`), INDEX \`IDX_b97a5a68c766d2d1ec25e6a85b\` (\`phone\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`offloads\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`priceTotal\` decimal(10,2) NOT NULL DEFAULT '0.00', \`paidMoney\` decimal(10,2) NOT NULL DEFAULT '0.00', \`delContainer1_7In\` decimal(5,0) NOT NULL DEFAULT '0', \`delContainer1_7Out\` decimal(5,0) NOT NULL DEFAULT '0', \`delContainer0_5In\` decimal(5,0) NOT NULL DEFAULT '0', \`delContainer0_5Out\` decimal(5,0) NOT NULL DEFAULT '0', \`delContainer0_4In\` decimal(5,0) NOT NULL DEFAULT '0', \`delContainer0_4Out\` decimal(5,0) NOT NULL DEFAULT '0', \`delContainerSchoellerIn\` decimal(5,0) NOT NULL DEFAULT '0', \`delContainerSchoellerOut\` decimal(5,0) NOT NULL DEFAULT '0', \`isClosed\` tinyint NULL DEFAULT 0, \`closureDescription\` varchar(255) NULL, \`boxTotalQuantity\` decimal(8,0) NOT NULL DEFAULT '0', \`authorId\` int NOT NULL, \`clientId\` int NOT NULL, \`driverId\` int NOT NULL, \`loaderShiftId\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`store-container\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`name\` varchar(35) NULL, \`amount\` decimal(10,0) NOT NULL DEFAULT '0', \`weight\` decimal(10,2) NOT NULL DEFAULT '0.00', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`waves\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`order\` decimal(2,0) NOT NULL DEFAULT '0', \`dateFrom\` date NOT NULL, \`dateTo\` date NULL, \`batchId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`storages\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`date\` date NOT NULL, \`amount\` decimal(10,2) NOT NULL DEFAULT '0.00', \`waveId\` int NULL, \`varietyId\` int NULL, \`categoryId\` int NULL, INDEX \`IDX_e55034cc2d1446efd0d3e65452\` (\`date\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`varieties\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`name\` varchar(35) NULL, \`isCutterPaid\` tinyint NULL DEFAULT 0, INDEX \`IDX_119f6fc825074d6121c59026c7\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`offload-records\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`boxQuantity\` decimal(5,0) NOT NULL DEFAULT '0', \`cuttingDate\` date NOT NULL, \`priceId\` decimal(16,0) NOT NULL DEFAULT '0', \`pricePerKg\` decimal(10,2) NOT NULL DEFAULT '0.00', \`weight\` decimal(10,2) NOT NULL DEFAULT '0.00', \`netWeight\` decimal(10,2) NOT NULL DEFAULT '0.00', \`shrinkedNetWeight\` decimal(10,2) NOT NULL DEFAULT '0.00', \`batchId\` int NOT NULL, \`categoryId\` int NOT NULL, \`offloadId\` int NOT NULL, \`storeContainerId\` int NOT NULL, \`waveId\` int NOT NULL, \`varietyId\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`subbatch\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`compostLoadDate\` date NOT NULL, \`compostSupplier\` varchar(50) NULL, \`compostWeight\` decimal(10,2) NOT NULL DEFAULT '0.00', \`compostPrice\` decimal(10,2) NOT NULL DEFAULT '0.00', \`peatLoadDate\` date NOT NULL, \`peatSupplier\` varchar(50) NULL, \`peatWeight\` decimal(10,2) NOT NULL DEFAULT '0.00', \`peatPrice\` decimal(10,2) NOT NULL DEFAULT '0.00', \`batchId\` int NULL, \`categoryId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`categories\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`name\` varchar(100) NULL, \`description\` varchar(255) NULL, INDEX \`IDX_8b0be371d28245da6e4f4b6187\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cuttings\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`boxQuantity\` decimal(10,0) NOT NULL DEFAULT '0', \`trip\` decimal(10,0) NOT NULL DEFAULT '0', \`categoryId\` int NOT NULL, \`varietyId\` int NOT NULL, \`batchId\` int NOT NULL, \`waveId\` int NOT NULL, \`cutterShiftId\` int NOT NULL, \`authorId\` int NOT NULL, \`loaderShiftId\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`firstName\` varchar(35) NULL, \`lastName\` varchar(35) NULL, \`patronymic\` varchar(35) NULL, \`email\` varchar(254) NULL, \`phone\` varchar(15) NULL, \`password\` varchar(255) NULL, \`role\` enum ('1', '2') NOT NULL DEFAULT '2', \`position\` enum ('SUPERADMINISTRATOR', 'FOREMAN', 'OFFICE_ADMINISTRATOR') NOT NULL DEFAULT 'FOREMAN', \`permissions\` text NULL, \`isActive\` tinyint NULL, INDEX \`IDX_af99afb7cf88ce20aff6977e68\` (\`lastName\`), INDEX \`IDX_a000cca60bcf04454e72769949\` (\`phone\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`works\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`title\` varchar(35) NULL, \`isRegular\` tinyint NULL DEFAULT 1, \`price\` decimal(10,2) NOT NULL DEFAULT '0.00', \`workType\` enum ('WATERING', 'CUTTING', 'CUSTOM') NOT NULL DEFAULT 'CUSTOM', INDEX \`IDX_4efbf189b941c4cd29e278f87d\` (\`title\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`work-records\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`date\` date NOT NULL, \`percent\` decimal(3,2) NOT NULL DEFAULT '0.00', \`percentAmount\` decimal(10,2) NOT NULL DEFAULT '0.00', \`reward\` decimal(10,2) NOT NULL DEFAULT '0.00', \`recordGroupId\` decimal(15,0) NOT NULL DEFAULT '0', \`workId\` int NOT NULL, \`shiftId\` int NOT NULL, \`chamberId\` int NOT NULL, INDEX \`IDX_e81b5a92f93b7753219a7e5aa0\` (\`date\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`chambers\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`name\` varchar(35) NULL, \`area\` decimal(10,2) NOT NULL DEFAULT '0.00', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`batches\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`name\` varchar(8) NULL, \`briquetteQuantity\` decimal(10,2) NOT NULL DEFAULT '0.00', \`dateFrom\` date NOT NULL, \`dateTo\` date NULL, \`waveQuantity\` decimal(2,0) NOT NULL DEFAULT '0', \`chamberId\` int NULL, INDEX \`IDX_94a720d7a8b59c3310ca8dafe4\` (\`name\`), INDEX \`IDX_889cb3fca0bba41b8d78e41dd7\` (\`dateFrom\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`yields\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`date\` date NOT NULL, \`weight\` decimal(10,2) NOT NULL DEFAULT '0.00', \`boxQuantity\` decimal(5,0) NOT NULL DEFAULT '0', \`percent\` decimal(6,5) NOT NULL DEFAULT '0.00000', \`categoryId\` int NULL, \`varietyId\` int NULL, \`batchId\` int NULL, \`waveId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`prices\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`tenant\` enum ('BOX', 'KITCHEN', 'LITER', 'MEDICATED_LITER') NOT NULL DEFAULT 'BOX', \`price\` decimal(10,2) NOT NULL DEFAULT '0.00', \`date\` date NOT NULL, INDEX \`IDX_99ec643394985350747a09d1dc\` (\`tenant\`), INDEX \`IDX_a2ac58aaa17a5670baa46ca26f\` (\`date\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`employees_documents_public_file\` (\`employeesId\` int NOT NULL, \`publicFileId\` int NOT NULL, INDEX \`IDX_0aa448289d86bafa46ab602eae\` (\`employeesId\`), INDEX \`IDX_1049b28a79fc6aa15a2ca57710\` (\`publicFileId\`), PRIMARY KEY (\`employeesId\`, \`publicFileId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`employees_avatars_public_file\` (\`employeesId\` int NOT NULL, \`publicFileId\` int NOT NULL, INDEX \`IDX_1f22cce2d38f6857945c16967a\` (\`employeesId\`), INDEX \`IDX_2b725d402b0a3edfdb754370e4\` (\`publicFileId\`), PRIMARY KEY (\`employeesId\`, \`publicFileId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`clients_files_public_file\` (\`clientsId\` int NOT NULL, \`publicFileId\` int NOT NULL, INDEX \`IDX_f8c3c6ca6e5390e97d1718de9f\` (\`clientsId\`), INDEX \`IDX_2453759bfe3d25c55a4c7d7fb3\` (\`publicFileId\`), PRIMARY KEY (\`clientsId\`, \`publicFileId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`offloads_documents_public_file\` (\`offloadsId\` int NOT NULL, \`publicFileId\` int NOT NULL, INDEX \`IDX_6b5bf9c1df8a964fd466530ddc\` (\`offloadsId\`), INDEX \`IDX_34c378b2ef36d1cd21a21a01d0\` (\`publicFileId\`), PRIMARY KEY (\`offloadsId\`, \`publicFileId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`waterings\` ADD CONSTRAINT \`FK_a6803aaece5dc2e7d3f8f6b45b9\` FOREIGN KEY (\`shiftId\`) REFERENCES \`shifts\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`waterings\` ADD CONSTRAINT \`FK_911fae0bd5227677056eb35bc75\` FOREIGN KEY (\`batchId\`) REFERENCES \`batches\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shifts\` ADD CONSTRAINT \`FK_ac74b69d4e1307cf392660ace63\` FOREIGN KEY (\`employeeId\`) REFERENCES \`employees\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`offloads\` ADD CONSTRAINT \`FK_ac64717d1e3cc490e78428588e9\` FOREIGN KEY (\`authorId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`offloads\` ADD CONSTRAINT \`FK_37ce31b9a5733b42bfa2129471e\` FOREIGN KEY (\`clientId\`) REFERENCES \`clients\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`offloads\` ADD CONSTRAINT \`FK_287941f174418d59182eeb37279\` FOREIGN KEY (\`driverId\`) REFERENCES \`drivers\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`offloads\` ADD CONSTRAINT \`FK_897fe9e7787851d79ecf09904ce\` FOREIGN KEY (\`loaderShiftId\`) REFERENCES \`shifts\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`waves\` ADD CONSTRAINT \`FK_35837e33cb59c62630015bc8ae7\` FOREIGN KEY (\`batchId\`) REFERENCES \`batches\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`storages\` ADD CONSTRAINT \`FK_9fc77c15126327cc428a609ca72\` FOREIGN KEY (\`waveId\`) REFERENCES \`waves\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`storages\` ADD CONSTRAINT \`FK_76b7ddd03acca3e1198f83f3e3d\` FOREIGN KEY (\`varietyId\`) REFERENCES \`varieties\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`storages\` ADD CONSTRAINT \`FK_0d4fe1bc2461815f018ee4af512\` FOREIGN KEY (\`categoryId\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`offload-records\` ADD CONSTRAINT \`FK_da80ee2ee3e0c8e88d0762c3815\` FOREIGN KEY (\`batchId\`) REFERENCES \`batches\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`offload-records\` ADD CONSTRAINT \`FK_d6a3c17bb133664dfa82203a55a\` FOREIGN KEY (\`categoryId\`) REFERENCES \`categories\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`offload-records\` ADD CONSTRAINT \`FK_a301860daf46348ee2488afc10e\` FOREIGN KEY (\`offloadId\`) REFERENCES \`offloads\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`offload-records\` ADD CONSTRAINT \`FK_38a2d989923de17aac315f53a24\` FOREIGN KEY (\`storeContainerId\`) REFERENCES \`store-container\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`offload-records\` ADD CONSTRAINT \`FK_36ed45d0737cf63befbb0540794\` FOREIGN KEY (\`waveId\`) REFERENCES \`waves\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`offload-records\` ADD CONSTRAINT \`FK_e9085d4152053090407d233585f\` FOREIGN KEY (\`varietyId\`) REFERENCES \`varieties\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`subbatch\` ADD CONSTRAINT \`FK_7410c0ba443e87101962e645998\` FOREIGN KEY (\`batchId\`) REFERENCES \`batches\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`subbatch\` ADD CONSTRAINT \`FK_d7093bf549b4217651d4ed830c4\` FOREIGN KEY (\`categoryId\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cuttings\` ADD CONSTRAINT \`FK_976029b3a83a00ec835eea27df5\` FOREIGN KEY (\`categoryId\`) REFERENCES \`categories\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`cuttings\` ADD CONSTRAINT \`FK_696381b0e4f6e2b2c7cf7558cb7\` FOREIGN KEY (\`varietyId\`) REFERENCES \`varieties\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`cuttings\` ADD CONSTRAINT \`FK_91b372104fa6a91c62229cf35fb\` FOREIGN KEY (\`batchId\`) REFERENCES \`batches\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`cuttings\` ADD CONSTRAINT \`FK_91a015582a3f197e46ccf3ca01b\` FOREIGN KEY (\`waveId\`) REFERENCES \`waves\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`cuttings\` ADD CONSTRAINT \`FK_e145d432fe3174934057da1e8ed\` FOREIGN KEY (\`cutterShiftId\`) REFERENCES \`shifts\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`cuttings\` ADD CONSTRAINT \`FK_551e1a1071331d4079ed0ec8afd\` FOREIGN KEY (\`authorId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`cuttings\` ADD CONSTRAINT \`FK_3d8879e8757656cd007c9183620\` FOREIGN KEY (\`loaderShiftId\`) REFERENCES \`shifts\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`work-records\` ADD CONSTRAINT \`FK_34f50aeaf8c463d9a98086d20c8\` FOREIGN KEY (\`workId\`) REFERENCES \`works\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`work-records\` ADD CONSTRAINT \`FK_8b2db07030e0784e9df8fa62d31\` FOREIGN KEY (\`shiftId\`) REFERENCES \`shifts\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`work-records\` ADD CONSTRAINT \`FK_fd9fbd18b5e6018ae24c38d064f\` FOREIGN KEY (\`chamberId\`) REFERENCES \`chambers\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`batches\` ADD CONSTRAINT \`FK_43cdd42370021bbac239841481b\` FOREIGN KEY (\`chamberId\`) REFERENCES \`chambers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`yields\` ADD CONSTRAINT \`FK_ecd2f323d124d76df856fc661d1\` FOREIGN KEY (\`categoryId\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`yields\` ADD CONSTRAINT \`FK_47927babc7b1de627d5b33793e2\` FOREIGN KEY (\`varietyId\`) REFERENCES \`varieties\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`yields\` ADD CONSTRAINT \`FK_fe834e250e71a100a014d8bbfdf\` FOREIGN KEY (\`batchId\`) REFERENCES \`batches\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`yields\` ADD CONSTRAINT \`FK_f9074a1457433d53ca8cd33be4a\` FOREIGN KEY (\`waveId\`) REFERENCES \`waves\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`employees_documents_public_file\` ADD CONSTRAINT \`FK_0aa448289d86bafa46ab602eae5\` FOREIGN KEY (\`employeesId\`) REFERENCES \`employees\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`employees_documents_public_file\` ADD CONSTRAINT \`FK_1049b28a79fc6aa15a2ca577102\` FOREIGN KEY (\`publicFileId\`) REFERENCES \`public_file\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`employees_avatars_public_file\` ADD CONSTRAINT \`FK_1f22cce2d38f6857945c16967a7\` FOREIGN KEY (\`employeesId\`) REFERENCES \`employees\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`employees_avatars_public_file\` ADD CONSTRAINT \`FK_2b725d402b0a3edfdb754370e46\` FOREIGN KEY (\`publicFileId\`) REFERENCES \`public_file\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`clients_files_public_file\` ADD CONSTRAINT \`FK_f8c3c6ca6e5390e97d1718de9f3\` FOREIGN KEY (\`clientsId\`) REFERENCES \`clients\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`clients_files_public_file\` ADD CONSTRAINT \`FK_2453759bfe3d25c55a4c7d7fb3a\` FOREIGN KEY (\`publicFileId\`) REFERENCES \`public_file\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`offloads_documents_public_file\` ADD CONSTRAINT \`FK_6b5bf9c1df8a964fd466530ddc3\` FOREIGN KEY (\`offloadsId\`) REFERENCES \`offloads\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`offloads_documents_public_file\` ADD CONSTRAINT \`FK_34c378b2ef36d1cd21a21a01d0e\` FOREIGN KEY (\`publicFileId\`) REFERENCES \`public_file\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`offloads_documents_public_file\` DROP FOREIGN KEY \`FK_34c378b2ef36d1cd21a21a01d0e\``);
        await queryRunner.query(`ALTER TABLE \`offloads_documents_public_file\` DROP FOREIGN KEY \`FK_6b5bf9c1df8a964fd466530ddc3\``);
        await queryRunner.query(`ALTER TABLE \`clients_files_public_file\` DROP FOREIGN KEY \`FK_2453759bfe3d25c55a4c7d7fb3a\``);
        await queryRunner.query(`ALTER TABLE \`clients_files_public_file\` DROP FOREIGN KEY \`FK_f8c3c6ca6e5390e97d1718de9f3\``);
        await queryRunner.query(`ALTER TABLE \`employees_avatars_public_file\` DROP FOREIGN KEY \`FK_2b725d402b0a3edfdb754370e46\``);
        await queryRunner.query(`ALTER TABLE \`employees_avatars_public_file\` DROP FOREIGN KEY \`FK_1f22cce2d38f6857945c16967a7\``);
        await queryRunner.query(`ALTER TABLE \`employees_documents_public_file\` DROP FOREIGN KEY \`FK_1049b28a79fc6aa15a2ca577102\``);
        await queryRunner.query(`ALTER TABLE \`employees_documents_public_file\` DROP FOREIGN KEY \`FK_0aa448289d86bafa46ab602eae5\``);
        await queryRunner.query(`ALTER TABLE \`yields\` DROP FOREIGN KEY \`FK_f9074a1457433d53ca8cd33be4a\``);
        await queryRunner.query(`ALTER TABLE \`yields\` DROP FOREIGN KEY \`FK_fe834e250e71a100a014d8bbfdf\``);
        await queryRunner.query(`ALTER TABLE \`yields\` DROP FOREIGN KEY \`FK_47927babc7b1de627d5b33793e2\``);
        await queryRunner.query(`ALTER TABLE \`yields\` DROP FOREIGN KEY \`FK_ecd2f323d124d76df856fc661d1\``);
        await queryRunner.query(`ALTER TABLE \`batches\` DROP FOREIGN KEY \`FK_43cdd42370021bbac239841481b\``);
        await queryRunner.query(`ALTER TABLE \`work-records\` DROP FOREIGN KEY \`FK_fd9fbd18b5e6018ae24c38d064f\``);
        await queryRunner.query(`ALTER TABLE \`work-records\` DROP FOREIGN KEY \`FK_8b2db07030e0784e9df8fa62d31\``);
        await queryRunner.query(`ALTER TABLE \`work-records\` DROP FOREIGN KEY \`FK_34f50aeaf8c463d9a98086d20c8\``);
        await queryRunner.query(`ALTER TABLE \`cuttings\` DROP FOREIGN KEY \`FK_3d8879e8757656cd007c9183620\``);
        await queryRunner.query(`ALTER TABLE \`cuttings\` DROP FOREIGN KEY \`FK_551e1a1071331d4079ed0ec8afd\``);
        await queryRunner.query(`ALTER TABLE \`cuttings\` DROP FOREIGN KEY \`FK_e145d432fe3174934057da1e8ed\``);
        await queryRunner.query(`ALTER TABLE \`cuttings\` DROP FOREIGN KEY \`FK_91a015582a3f197e46ccf3ca01b\``);
        await queryRunner.query(`ALTER TABLE \`cuttings\` DROP FOREIGN KEY \`FK_91b372104fa6a91c62229cf35fb\``);
        await queryRunner.query(`ALTER TABLE \`cuttings\` DROP FOREIGN KEY \`FK_696381b0e4f6e2b2c7cf7558cb7\``);
        await queryRunner.query(`ALTER TABLE \`cuttings\` DROP FOREIGN KEY \`FK_976029b3a83a00ec835eea27df5\``);
        await queryRunner.query(`ALTER TABLE \`subbatch\` DROP FOREIGN KEY \`FK_d7093bf549b4217651d4ed830c4\``);
        await queryRunner.query(`ALTER TABLE \`subbatch\` DROP FOREIGN KEY \`FK_7410c0ba443e87101962e645998\``);
        await queryRunner.query(`ALTER TABLE \`offload-records\` DROP FOREIGN KEY \`FK_e9085d4152053090407d233585f\``);
        await queryRunner.query(`ALTER TABLE \`offload-records\` DROP FOREIGN KEY \`FK_36ed45d0737cf63befbb0540794\``);
        await queryRunner.query(`ALTER TABLE \`offload-records\` DROP FOREIGN KEY \`FK_38a2d989923de17aac315f53a24\``);
        await queryRunner.query(`ALTER TABLE \`offload-records\` DROP FOREIGN KEY \`FK_a301860daf46348ee2488afc10e\``);
        await queryRunner.query(`ALTER TABLE \`offload-records\` DROP FOREIGN KEY \`FK_d6a3c17bb133664dfa82203a55a\``);
        await queryRunner.query(`ALTER TABLE \`offload-records\` DROP FOREIGN KEY \`FK_da80ee2ee3e0c8e88d0762c3815\``);
        await queryRunner.query(`ALTER TABLE \`storages\` DROP FOREIGN KEY \`FK_0d4fe1bc2461815f018ee4af512\``);
        await queryRunner.query(`ALTER TABLE \`storages\` DROP FOREIGN KEY \`FK_76b7ddd03acca3e1198f83f3e3d\``);
        await queryRunner.query(`ALTER TABLE \`storages\` DROP FOREIGN KEY \`FK_9fc77c15126327cc428a609ca72\``);
        await queryRunner.query(`ALTER TABLE \`waves\` DROP FOREIGN KEY \`FK_35837e33cb59c62630015bc8ae7\``);
        await queryRunner.query(`ALTER TABLE \`offloads\` DROP FOREIGN KEY \`FK_897fe9e7787851d79ecf09904ce\``);
        await queryRunner.query(`ALTER TABLE \`offloads\` DROP FOREIGN KEY \`FK_287941f174418d59182eeb37279\``);
        await queryRunner.query(`ALTER TABLE \`offloads\` DROP FOREIGN KEY \`FK_37ce31b9a5733b42bfa2129471e\``);
        await queryRunner.query(`ALTER TABLE \`offloads\` DROP FOREIGN KEY \`FK_ac64717d1e3cc490e78428588e9\``);
        await queryRunner.query(`ALTER TABLE \`shifts\` DROP FOREIGN KEY \`FK_ac74b69d4e1307cf392660ace63\``);
        await queryRunner.query(`ALTER TABLE \`waterings\` DROP FOREIGN KEY \`FK_911fae0bd5227677056eb35bc75\``);
        await queryRunner.query(`ALTER TABLE \`waterings\` DROP FOREIGN KEY \`FK_a6803aaece5dc2e7d3f8f6b45b9\``);
        await queryRunner.query(`DROP INDEX \`IDX_34c378b2ef36d1cd21a21a01d0\` ON \`offloads_documents_public_file\``);
        await queryRunner.query(`DROP INDEX \`IDX_6b5bf9c1df8a964fd466530ddc\` ON \`offloads_documents_public_file\``);
        await queryRunner.query(`DROP TABLE \`offloads_documents_public_file\``);
        await queryRunner.query(`DROP INDEX \`IDX_2453759bfe3d25c55a4c7d7fb3\` ON \`clients_files_public_file\``);
        await queryRunner.query(`DROP INDEX \`IDX_f8c3c6ca6e5390e97d1718de9f\` ON \`clients_files_public_file\``);
        await queryRunner.query(`DROP TABLE \`clients_files_public_file\``);
        await queryRunner.query(`DROP INDEX \`IDX_2b725d402b0a3edfdb754370e4\` ON \`employees_avatars_public_file\``);
        await queryRunner.query(`DROP INDEX \`IDX_1f22cce2d38f6857945c16967a\` ON \`employees_avatars_public_file\``);
        await queryRunner.query(`DROP TABLE \`employees_avatars_public_file\``);
        await queryRunner.query(`DROP INDEX \`IDX_1049b28a79fc6aa15a2ca57710\` ON \`employees_documents_public_file\``);
        await queryRunner.query(`DROP INDEX \`IDX_0aa448289d86bafa46ab602eae\` ON \`employees_documents_public_file\``);
        await queryRunner.query(`DROP TABLE \`employees_documents_public_file\``);
        await queryRunner.query(`DROP INDEX \`IDX_a2ac58aaa17a5670baa46ca26f\` ON \`prices\``);
        await queryRunner.query(`DROP INDEX \`IDX_99ec643394985350747a09d1dc\` ON \`prices\``);
        await queryRunner.query(`DROP TABLE \`prices\``);
        await queryRunner.query(`DROP TABLE \`yields\``);
        await queryRunner.query(`DROP INDEX \`IDX_889cb3fca0bba41b8d78e41dd7\` ON \`batches\``);
        await queryRunner.query(`DROP INDEX \`IDX_94a720d7a8b59c3310ca8dafe4\` ON \`batches\``);
        await queryRunner.query(`DROP TABLE \`batches\``);
        await queryRunner.query(`DROP TABLE \`chambers\``);
        await queryRunner.query(`DROP INDEX \`IDX_e81b5a92f93b7753219a7e5aa0\` ON \`work-records\``);
        await queryRunner.query(`DROP TABLE \`work-records\``);
        await queryRunner.query(`DROP INDEX \`IDX_4efbf189b941c4cd29e278f87d\` ON \`works\``);
        await queryRunner.query(`DROP TABLE \`works\``);
        await queryRunner.query(`DROP INDEX \`IDX_a000cca60bcf04454e72769949\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_af99afb7cf88ce20aff6977e68\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP TABLE \`cuttings\``);
        await queryRunner.query(`DROP INDEX \`IDX_8b0be371d28245da6e4f4b6187\` ON \`categories\``);
        await queryRunner.query(`DROP TABLE \`categories\``);
        await queryRunner.query(`DROP TABLE \`subbatch\``);
        await queryRunner.query(`DROP TABLE \`offload-records\``);
        await queryRunner.query(`DROP INDEX \`IDX_119f6fc825074d6121c59026c7\` ON \`varieties\``);
        await queryRunner.query(`DROP TABLE \`varieties\``);
        await queryRunner.query(`DROP INDEX \`IDX_e55034cc2d1446efd0d3e65452\` ON \`storages\``);
        await queryRunner.query(`DROP TABLE \`storages\``);
        await queryRunner.query(`DROP TABLE \`waves\``);
        await queryRunner.query(`DROP TABLE \`store-container\``);
        await queryRunner.query(`DROP TABLE \`offloads\``);
        await queryRunner.query(`DROP INDEX \`IDX_b97a5a68c766d2d1ec25e6a85b\` ON \`drivers\``);
        await queryRunner.query(`DROP INDEX \`IDX_d3a9115337268e2413392a8ac4\` ON \`drivers\``);
        await queryRunner.query(`DROP TABLE \`drivers\``);
        await queryRunner.query(`DROP INDEX \`IDX_aa22377d7d3e794ae4cd39cd9e\` ON \`clients\``);
        await queryRunner.query(`DROP INDEX \`IDX_8a28b1e0e38fc81165d5dac229\` ON \`clients\``);
        await queryRunner.query(`DROP TABLE \`clients\``);
        await queryRunner.query(`DROP TABLE \`public_file\``);
        await queryRunner.query(`DROP INDEX \`IDX_cbc362d1c574464a63d3acc3ea\` ON \`employees\``);
        await queryRunner.query(`DROP INDEX \`IDX_c7496c7e6508db62ba4da839b3\` ON \`employees\``);
        await queryRunner.query(`DROP TABLE \`employees\``);
        await queryRunner.query(`DROP INDEX \`IDX_3a0e6f3a0fae1e7fac5ca3801d\` ON \`shifts\``);
        await queryRunner.query(`DROP TABLE \`shifts\``);
        await queryRunner.query(`DROP INDEX \`IDX_657441e38570083f56caad3536\` ON \`waterings\``);
        await queryRunner.query(`DROP TABLE \`waterings\``);
    }

}
